### ISSUE TITLE
Practica6-Hilos

### ISSUE THREAD

**Issue by IrvingFernand0** [SistemasTecTlaxiaco/practica-de-hilos-IrvingFernand0#2]
[practica6-TA_IrvingFernandoReyesPacheco.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-IrvingFernand0/files/8439534/practica6-TA_IrvingFernandoReyesPacheco.pdf)

**Comment by Sandra631** [comment]
19% bien hecho

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
